[package]
name = "tessera"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
gtk = { package = "gtk4", version = "0.11" }
adw = { package = "libadwaita", version = "0.9", features = ["v1_4"] }
vte = { package = "vte4", version = "0.10" }
gio = "0.22"
glib = "0.22"
anyhow = "1"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
